package com.example.wafarlytask.models.order_details_response_model

data class OrderDetailsResponse(
    val barcode: String,
    val cashierComment: Any,
    val cashierUser: Any,
    val couponCode: Any,
    val createdDate: String,
    val customerServiceComment: Any,
    val customerServiceUser: CustomerServiceUser,
    val customerUser: CustomerUser,
    val discountAmount: Int,
    val grandTotal: Double,
    val id: Int,
    val idOnline: Any,
    val inventory: Inventory,
    val merchantName: String,
    val operationNumber: Any,
    val orderDetails: List<OrderDetail>,
    val orderNumber: String,
    val paymentDeliveryMethod: Int,
    val paymentMethod: Int,
    val postponedDate: String,
    val priceAfterDiscountTotal: Int,
    val receivedFromDelivery: Double,
    val serviceFee: Double,
    val shippingAddresses: List<ShippingAddresse>,
    val shippingAmount: Double,
    val shippingMethod: Int,
    val startCompleteDate: Any,
    val startShippingDate: Any,
    val status: Int,
    val syncSucceed: Boolean,
    val totalRefunded: Int
)