package com.example.wafarlytask.models.orders_response

data class Item(
    val cashierComment: Any,
    val cashierUser: Any,
    val couponCode: Any,
    val createdDate: String,
    val customerServiceComment: Any,
    val customerServiceUser: CustomerServiceUser,
    val customerUser: CustomerUser,
    val deliveryUser: Any,
    val discountAmount: Int,
    val fromPos: Boolean,
    val grandTotal: Double,
    val id: Int,
    val idOnline: Any,
    val inventory: Inventory,
    val merchantId: String,
    val operationNumber: Any,
    val orderNumber: String,
    val paymentMethod: Int,
    val postponedDate: String,
    val preparingOrderEmployeeUser: Any,
    val priceAfterDiscountTotal: Int,
    val purchasePoint: Int,
    val serviceFee: Double,
    val shippingAddresses: List<ShippingAddresse>,
    val shippingAmount: Double,
    val shippingMethod: Int,
    val startCompleteDate: Any,
    val startShippingDate: Any,
    val status: Int,
    val syncSucceed: Boolean,
    val totalRefunded: Int,
    val updatedDate: String
)